// Code generated by "stringer -type=OperatorType -trimprefix=OperatorType_ -output=operator_string.go operator.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperatorType_None_Default-0]
	_ = x[OperatorType_NOT-1]
	_ = x[OperatorType_MUL-2]
	_ = x[OperatorType_ADD-3]
	_ = x[OperatorType_SUB-4]
	_ = x[OperatorType_QUO-5]
	_ = x[OperatorType_LESS-6]
	_ = x[OperatorType_GREATER-7]
	_ = x[OperatorType_NOT_EQ-8]
	_ = x[OperatorType_AND-9]
	_ = x[OperatorType_LESS_EQ-10]
	_ = x[OperatorType_EQ_EQ-11]
	_ = x[OperatorType_GR_EQ-12]
	_ = x[OperatorType_OR-13]
	_ = x[OperatorType_BIT_AND-14]
	_ = x[OperatorType_BIT_OR-15]
	_ = x[OperatorType_BIT_XOR-16]
	_ = x[OperatorType_MOD-17]
	_ = x[OperatorType_LSHIFT-18]
	_ = x[OperatorType_RSHIFT-19]
	_ = x[OperatorType_ADD_EQ-20]
	_ = x[OperatorType_SUB_EQ-21]
	_ = x[OperatorType_MUL_EQ-22]
	_ = x[OperatorType_DIV_EQ-23]
	_ = x[OperatorType_MOD_EQ-24]
	_ = x[OperatorType_LSHIFT_EQ-25]
	_ = x[OperatorType_RSHIFT_EQ-26]
	_ = x[OperatorType_BIT_AND_EQ-27]
	_ = x[OperatorType_BIT_OR_EQ-28]
	_ = x[OperatorType_BIT_XOR_EQ-29]
	_ = x[OperatorType_INC-30]
	_ = x[OperatorType_DEC-31]
}

const _OperatorType_name = "None_DefaultNOTMULADDSUBQUOLESSGREATERNOT_EQANDLESS_EQEQ_EQGR_EQORBIT_ANDBIT_ORBIT_XORMODLSHIFTRSHIFTADD_EQSUB_EQMUL_EQDIV_EQMOD_EQLSHIFT_EQRSHIFT_EQBIT_AND_EQBIT_OR_EQBIT_XOR_EQINCDEC"

var _OperatorType_index = [...]uint8{0, 12, 15, 18, 21, 24, 27, 31, 38, 44, 47, 54, 59, 64, 66, 73, 79, 86, 89, 95, 101, 107, 113, 119, 125, 131, 140, 149, 159, 168, 178, 181, 184}

func (i OperatorType) String() string {
	if i < 0 || i >= OperatorType(len(_OperatorType_index)-1) {
		return "OperatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperatorType_name[_OperatorType_index[i]:_OperatorType_index[i+1]]
}
